name: Build Breadwallet Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install Android SDK
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip
        unzip -qq android-sdk-tools.zip -d $HOME/android-sdk
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/cmdline-tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

    - name: Build project
      run: |
        cd breadwallet-android
        ./gradlew build

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: breadwallet-apk
        path: breadwallet-android/app/build/outputs/apk/debug/*.apk
