name: Build Breadwallet Android

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Android SDK
      uses: android/setup-android@v2
      with:
        sdk-platform: '30'
        sdk-build-tools: '30.0.3'
    - name: Build project
      run: |
        cd breadwallet-android
        ./gradlew build

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: breadwallet-apk
        path: breadwallet-android/app/build/outputs/apk/debug/*.apk
